/*
 * File: app/view/Demo.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Demo', {
    extend: 'Ext.form.Panel',

    config: {
        fieldDefaults: {
            labelWidth: 80
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Form Validation Example'
            },
            {
                xtype: 'fieldset',
                title: 'Enter Your Name',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'First Name',
                        name: 'fname',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Last Name',
                        name: 'lname',
                        required: true
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                layout: {
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            var errorString = '',
                                form = button.up('formpanel'),
                                fields = form.query("field");

                            for (var i=0; i<fields.length; i++) {
                                fields[i].removeCls('invalidField');
                            }

                            var model = Ext.create("MyApp.model.Person", form.getValues());

                            var errors = model.validate();

                            if (!errors.isValid()) {
                                errors.each(function (errorObj){
                                    errorString += errorObj.getField() + " " + errorObj.getMessage() + "<br />";
                                    var s = Ext.String.format('field[name={0}]',errorObj.getField());
                                    form.down(s).addCls('invalidField');
                                });
                                Ext.Msg.alert('Errors in your input',errorString);
                            } else {
                                Ext.Msg.alert("Data is valid","Success");   
                            }
                        },
                        text: 'Submit'
                    }
                ]
            }
        ]
    }

});